Updated requirements.txt
Was getting this error because of latest version of discord.py 

Error Code:
```
2022-08-09 07:13:57 WARNING [例外][702947208139505674]<class 'discord.app_commands.errors.CommandInvokeError'>: Command 'showcase角色展示櫃' raised an exception: AttributeError: 'Interaction' object has no attribute 'edit_original_message'
```

Fixed it by changing the discord.py version